#!/usr/bin/env node
// Emit seed SQL for Ostiary on stdout.
//
//   node scripts/seed.mjs            > .seed.sql
//   node scripts/seed.mjs --demo     > .seed.sql   (adds sample ushers)
//
// Slot times are generated relative to today so the seed never goes stale.
// Every generated Mass time is flagged unconfirmed_time = 1: the real St.
// Clement schedule was NOT read off the parish website, and a roster built on
// guessed Mass times is worse than an empty one. The coordinator confirms them
// in the admin screen, which clears the flag.

import { pbkdf2Sync, randomBytes, randomUUID } from 'node:crypto';

const DEMO = process.argv.includes('--demo');
const NOW = Math.floor(Date.now() / 1000);
const PBKDF2_ITERATIONS = 210000; // OWASP 2023 floor for PBKDF2-HMAC-SHA256

// Dev-only default. Real deployments set OSTIARY_ADMIN_PASSPHRASE, and the
// coordinator changes it from the admin screen afterwards.
const PASSPHRASE = process.env.OSTIARY_ADMIN_PASSPHRASE || 'change-me-locally';
const JOIN_CODE = process.env.OSTIARY_JOIN_CODE || 'CLEMENT';

if (!process.env.OSTIARY_ADMIN_PASSPHRASE) {
    console.error('! OSTIARY_ADMIN_PASSPHRASE unset; seeding the dev passphrase.');
    console.error('! Do not run this against a remote database.');
}

// --- helpers ---------------------------------------------------------------

const q = (v) =>
    v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;

/** PBKDF2-SHA256, stored as "iterations:saltB64:hashB64". Verified in
 *  functions/_lib/auth.ts with Web Crypto, which uses the same primitive. */
function hashPassphrase(plain) {
    const salt = randomBytes(16);
    const hash = pbkdf2Sync(plain, salt, PBKDF2_ITERATIONS, 32, 'sha256');
    return `${PBKDF2_ITERATIONS}:${salt.toString('base64')}:${hash.toString('base64')}`;
}

/** Offset in minutes between UTC and a named zone at a given instant. */
function zoneOffsetMinutes(date, timeZone) {
    const fmt = new Intl.DateTimeFormat('en-US', {
        timeZone, hour12: false,
        year: 'numeric', month: '2-digit', day: '2-digit',
        hour: '2-digit', minute: '2-digit', second: '2-digit',
    });
    const p = Object.fromEntries(fmt.formatToParts(date).map((x) => [x.type, x.value]));
    const asUTC = Date.UTC(+p.year, +p.month - 1, +p.day, +p.hour % 24, +p.minute, +p.second);
    return (asUTC - date.getTime()) / 60000;
}

/** Unix seconds for a wall-clock time in a zone. Two passes settle DST, so a
 *  10:00 Mass stays 10:00 across the November change. */
function wallClockToUnix(y, m, d, hh, mm, timeZone) {
    let ts = Date.UTC(y, m - 1, d, hh, mm, 0);
    for (let i = 0; i < 2; i++) {
        const off = zoneOffsetMinutes(new Date(ts), timeZone);
        ts = Date.UTC(y, m - 1, d, hh, mm, 0) - off * 60000;
    }
    return Math.floor(ts / 1000);
}

/** The next `count` Sundays, starting with today if today is Sunday. */
function upcomingSundays(count) {
    const out = [];
    const cur = new Date();
    cur.setHours(12, 0, 0, 0);
    while (cur.getDay() !== 0) cur.setDate(cur.getDate() + 1);
    for (let i = 0; i < count; i++) {
        out.push([cur.getFullYear(), cur.getMonth() + 1, cur.getDate()]);
        cur.setDate(cur.getDate() + 7);
    }
    return out;
}

// --- rows ------------------------------------------------------------------

const TZ = 'America/Los_Angeles';
const parishId = 'st-clement-santa-monica';
const lines = [];
const say = (s) => lines.push(s);

say('-- Generated by scripts/seed.mjs. Do not edit; regenerate.');
say('PRAGMA foreign_keys = ON;');
say('');
// No explicit BEGIN/COMMIT: remote D1 rejects SQL transaction statements
// ("please use the state.storage.transaction() APIs"), and `wrangler d1
// execute --file` already applies the batch atomically on both targets.

say(`INSERT OR REPLACE INTO parishes
  (id, slug, name, city, state, timezone, join_code, admin_hash, policy_notes, created_at, updated_at)
VALUES (${q(parishId)}, ${q('st-clement-catholic-church')},
        ${q('St. Clement (by-the-Sea) Catholic Church')}, ${q('Santa Monica')}, ${q('CA')},
        ${q(TZ)}, ${q(JOIN_CODE)}, ${q(hashPassphrase(PASSPHRASE))},
        ${q('')}, ${NOW}, ${NOW});`);

const coordinatorId = 'usher-coordinator-seed';
say(`INSERT OR REPLACE INTO ushers
  (id, parish_id, name, email, phone, role, languages, active, notes, created_at, updated_at)
VALUES (${q(coordinatorId)}, ${q(parishId)}, ${q('Tom Ciszek')}, ${q('t@thomas.tc')}, NULL,
        ${q('coordinator')}, ${q('en')}, 1, ${q('Seeded coordinator.')}, ${NOW}, ${NOW});`);

if (DEMO) {
    // Clearly-labelled fixtures so screenshots have a populated roster.
    // Never seed these into a real parish database.
    const demo = [
        ['demo-1', 'Sample Usher One', 'usher',   'en,es'],
        ['demo-2', 'Sample Usher Two', 'captain', 'en'],
        ['demo-3', 'Sample Usher Three', 'usher', 'es'],
        ['demo-4', 'Sample Usher Four', 'usher',  'en'],
    ];
    for (const [id, name, role, langs] of demo) {
        say(`INSERT OR REPLACE INTO ushers
  (id, parish_id, name, email, phone, role, languages, active, notes, created_at, updated_at)
VALUES (${q(id)}, ${q(parishId)}, ${q(name)}, NULL, NULL, ${q(role)}, ${q(langs)}, 1,
        ${q('DEMO FIXTURE - not a real person')}, ${NOW}, ${NOW});`);
    }
}

// Placeholder Sunday Masses. Times are a plausible parish pattern, NOT the
// verified St. Clement schedule; unconfirmed_time = 1 makes the UI say so.
const PATTERN = [
    [8, 0, 'Sunday 8:00 Mass', 'en', 3],
    [10, 0, 'Sunday 10:00 Sung Mass', 'en', 4],
    [12, 0, 'Misa en Espanol 12:00', 'es', 4],
];

for (const [y, m, d] of upcomingSundays(8)) {
    for (const [hh, mm, label, lang, needed] of PATTERN) {
        const starts = wallClockToUnix(y, m, d, hh, mm, TZ);
        const id = `slot-${y}${String(m).padStart(2, '0')}${String(d).padStart(2, '0')}-${hh}`;
        say(`INSERT OR REPLACE INTO mass_slots
  (id, parish_id, starts_at, label, language, ushers_needed, notes, unconfirmed_time, created_at)
VALUES (${q(id)}, ${q(parishId)}, ${starts}, ${q(label)}, ${q(lang)}, ${needed},
        ${q('Seeded placeholder. Confirm against the parish schedule.')}, 1, ${NOW});`);
    }
}

// One upcoming meeting, two weeks out, 7pm local.
{
    const [y, m, d] = upcomingSundays(3)[2];
    const starts = wallClockToUnix(y, m, d, 19, 0, TZ);
    say(`INSERT OR REPLACE INTO meetings
  (id, parish_id, starts_at, title, location, agenda_md, minutes_md, created_at, updated_at)
VALUES (${q('meeting-seed-1')}, ${q(parishId)}, ${starts},
        ${q('Fall usher team meeting')}, ${q('Parish hall')},
        ${q('1. Welcome and prayer\n2. Confirm the Sunday Mass schedule\n3. Formation status\n4. Collection procedure walkthrough\n5. Questions')},
        NULL, ${NOW}, ${NOW});`);
}

process.stdout.write(lines.join('\n') + '\n');
